name: "Format and Lint"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  # required to make commits with corrected formatting
  contents: write

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # lets us cache the following devShell
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: osmosis
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Format and Lint
        run: |
          nix develop --accept-flake-config --command bash -c \
            'pre-commit run -a --show-diff-on-failure || exit 0'

      - name: Add and Commit
        if: ${{ github.event_name != 'pull_request' }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore(style): format and lint files"
