name: "Nix CI"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: osmosis
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: |
          nix build .#osmosis-frontend --print-build-logs --accept-flake-config
          nix build .#osmosis-nvidia --print-build-logs --accept-flake-config
          nix build .#osmosis-amd --print-build-logs --accept-flake-config
