name: "Nix CI"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [osmosis-amd, osmosis-nvidia]

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: osmosis
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          nix build --accept-flake-config --fallback -Lv .#${{ matrix.package }}
